version: '3.8'

services:
  frontend:
    image: 'pmt-app'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '4201:4200'
    networks:
      - frontend


 # backend:
 #   image: 'pmt-backend'
 #   build:
 #     context: ./backend
 #     dockerfile: Dockerfile
 #   ports:
 #     - '8081:8081'
 #   depends_on:
 #     - mysql
 #   networks:
 #     - backend


  adminer:
    image: 'adminer'
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    networks:
      - backend
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=pmtdb'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

networks:
  backend:
  frontend: