services:
  frontend:
    image: 'pmt-app'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
  adminer:
    image: 'adminer'
    restart: always
    ports:
      - '8080:8080'
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=pmtdb'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
