name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: pmtdb
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: verysecret
          MYSQL_USER: myuser
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libgconf-2-4

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build Angular app
        run: npm run build --prod
        working-directory: ./frontend

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./frontend/coverage

      - name: Run tests
        run: npm test
        working-directory: ./frontend

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker Compose
        run: docker-compose up --build -d
        working-directory: .

      - name: Wait for services to be healthy
        run: |
          while ! docker-compose ps | grep "healthy"; do
            echo "Waiting for services to be healthy..."
            sleep 10
          done
        working-directory: .

      - name: Verify services
        run: curl -f http://localhost:4201 || exit 1